### ISSUE TITLE
Code failed to run

### ISSUE THREAD

**Issue by z1047310438** [chamathpali/FedSim#3]
Hello, after I installed the environment according to what you said, the code cannot run and there are always missing things. But my python version is 3.7.13. But it seems that it is not a problem with the python version, but because there is no corresponding file.

**Comment by chamathpali** [comment]
@z1047310438 can you send a screenshot or the text of the error appearing?

**Comment by z1047310438** [comment]
For example, if I execute this command bash run_fedsim.sh mnist 0 9 20 mnist_run, the error in the picture will appear, and there is no data file in the data/mnist folder.
![微信图片_20231202195711](https://github.com/chamathpali/FedSim/assets/92215857/c7a20ba5-91af-4341-a294-7c0b124cbc8e)
![image](https://github.com/chamathpali/FedSim/assets/92215857/0bd35713-eec8-46dd-8153-80a9b994fa53)

**Comment by z1047310438** [comment]
But if I change the command bash run_fedsim.sh mex 0 9 20 mex_run, it can be executed normally.

**Comment by z1047310438** [comment]
And I still have a question why do I need to create the folder myself. For example, when I execute bash run_fedsim.sh mex 0 9 20 mex_run, I must also create a csv file of the corresponding data set in the fedavg_original folder.

**Comment by z1047310438** [comment]
I use another data set, the rnn model, but in the end there will be an error finding embs.json. Do I need to create this myself?
![image](https://github.com/chamathpali/FedSim/assets/92215857/a012ee14-8954-4924-ae52-ffb483dfa13b)
![image](https://github.com/chamathpali/FedSim/assets/92215857/d9f88885-6433-4f45-bb2b-aaed041b365f)

**Comment by z1047310438** [comment]
@chamathpali Looking forward to your answer. Thank you.

**Comment by chamathpali** [comment]
@z1047310438 the issue seems that you have no data in the folders to execute the mnist command. 
In each data folder there is a Readme file on how to create the dataset 
e.g. https://github.com/chamathpali/FedSim/tree/main/data/mnist#readme

And for your next question. here is the breakdown for this command
`bash run_fedsim.sh mex 0 9 20 mex_run`
run_fedsim.sh = the algorithm you are running
mex = dataset
0 = drop percentage (used for fedprox)
9 = number of fedsim clusters
20 = number of clients selected per round
mex_run = experiment name (you can put any string here)

(also you can see the full information here https://github.com/chamathpali/FedSim/blob/main/run_fedsim.sh numbered $1-$4

So for each dataset there is a selected parameter config
e.g. For MEx there are only 30 total clients in the dataset so we use only 10 clients per rounds, thats why there is no file in the original folder

In the paper we selected the following parameters and the original files and commands are for those.
<img width="733" alt="Screenshot 2023-12-02 at 21 14 46" src="https://github.com/chamathpali/FedSim/assets/5123109/f5f43c89-844a-4e31-853e-f682a7e0acbd">

So if you want to do a brand new dataset and a different config you can do a full run without the graph being generated from here https://github.com/chamathpali/FedSim/blob/main/utils/csv_log.py#L50 
Once you have the values for a single run you can create the original file from it in the same format. also make sure to check the names its 
```
mnist_20.csv 
mnist_20_prox.csv
```
Where 20 is the number of clients per round

Regarding the embs.json, yes you can generate it locally with the dataset guide here https://github.com/chamathpali/Fed-Goodreads because the file is around 1.1GB in size.

**Comment by z1047310438** [comment]
Thank you for your answer, thank you very much
